# Generated by Django 6.0.3 on 2026-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(default='actualidad', max_length=50),
            preserve_default=False,
        ),
    ]
